# Generated by Django 4.0.4 on 2023-02-23 06:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('min_remuneration', models.IntegerField(default=0)),
                ('max_remuneration', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=20)),
                ('is_hourly', models.BooleanField(default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('proposals', models.CharField(max_length=50)),
                ('job_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
