# Generated by Django 4.0.4 on 2023-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='max_remuneration',
            new_name='max_amount',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='min_remuneration',
            new_name='min_amount',
        ),
        migrations.AddField(
            model_name='job',
            name='feed_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
