# Generated by Django 4.0.4 on 2023-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_max_remuneration_job_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.CharField(max_length=50),
        ),
    ]
